-- List all customers
SELECT * FROM Customers;

-- List name and price of dishes
SELECT Name, Price FROM Dishes;

-- List all dishes that cost more than $15
SELECT Name from dishes where price>15;

-- Number of customers
SELECT COUNT(*) FROM Customers;

-- Number of orders
SELECT COUNT(*) FROM Orders;

-- List customers from specific City
SELECT CustomerID, FirstName, LastName FROM Customers
WHERE City='Washington';

-- Total Orders per Customer
SELECT c.CustomerID, FirstName, LastName, COUNT(OrderID) as counter
FROM Customers as c LEFT JOIN Orders as o ON c.CustomerID=o.CustomerID
GROUP BY c.CustomerID
ORDER BY counter DESC;

-- Most Popular Dishes
SELECT
d.Name,
COUNT(*) AS total_orders
FROM OrdersDishes od
JOIN Dishes d
ON od.DishID = d.DishID
GROUP BY d.Name
ORDER BY total_orders DESC;

-- Revenue Generated by each dish
SELECT
d.Name,
SUM(d.Price) AS revenue
FROM OrdersDishes od
JOIN Dishes d
ON od.DishID = d.DishID
GROUP BY d.Name
ORDER BY revenue DESC;

-- Number of Reservations per day
SELECT strftime('%Y',Date) as yr, strftime('%m',Date) as mth, strftime('%d', Date) as day, COUNT(*) FROM Reservations
GROUP BY day;

-- Customers who attended Events
SELECT c.CustomerID, c.EventID, Name, cu.FirstName, cu.LastName FROM CustomersEvents as c
INNER JOIN Events as e ON
c.EventID=e.EventID
LEFT JOIN Customers as cu on c.CustomerID=cu.CustomerID;

-- List all customers
SELECT FirstName, LastName, Email, City, State FROM Customers;

-- Dishes by Price Descending
SELECT Name, Price FROM Dishes 
ORDER BY Price Desc;

-- Show dishes between 7 and 9 dollars
SELECT Name, Price FROM Dishes
WHERE Price BETWEEN 7 and 9
ORDER BY Price Desc;

-- Count number of reservations each day
SELECT COUNT(ReservationID) as nums, strftime('%d',Date) as day FROM Reservations
GROUP BY day;

-- Average party size
SELECT AVG(PartySize) FROM Reservations;

-- Average party size per day
SELECT AVG(PartySize) as avg_size, strftime('%d',Date) as day FROM Reservations
GROUP BY day;

-- The events and locations
SELECT DISTINCT Name, Location FROM Events;

-- Number of customers with favorite dish
SELECT COUNT(DISTINCT CustomerID) as num_customers FROM Customers
WHERE FavoriteDish IS NOT NULL;

-- Customers born in September
SELECT strftime('%m', Birthday) as mth, FirstName, LastName FROM Customers
WHERE mth='09';

